# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script SriRama'
  
- task: Maven@3
  inputs:
  mavenPomFile: 'https://github.com/chetanabheemesh/hello-world/blob/master/pom.xml'
  
- script:
      echo Add other tasks to build, test, and deploy your project 25 August 2021.
      echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script Yahoo!!'
